# -*- coding: utf-8 -*-
"""share_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LzKJNAaMD2oOjUsqx_fKw8q6NjQzj-l1
"""

import networkx as nx
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

var1=yf.Ticker('AAPL')
apple=var1.institutional_holders

apple['comp']=var1.ticker

var2=yf.Ticker("MSFT")
microsoft=var2.institutional_holders

microsoft['comp']=var2.ticker

df=pd.concat([apple,microsoft])

G=nx.from_pandas_edgelist(df,source='Holder',target='comp',edge_attr='Shares')

nx.draw(G,with_labels=True)
plt.show()

tickers=pd.read_html("https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average")

tickers=tickers[2].Symbol.to_list()

frames=[]
for ticker in tickers:
  var=yf.Ticker(ticker)
  frame=var.institutional_holders
  frame['comp']=ticker
  frames.append(frame)

all_tog=pd.concat(frames)

G=nx.from_pandas_edgelist(all_tog, 'Holder', 'comp',edge_attr=True)

colors = []
target_nodes = set(all_tog['comp'].values)

for node in G:
    if node in target_nodes:
        colors.append("red")
    else:
        colors.append("yellow")

node_size_list=[v*100 for v in dict(G.degree()).values()]

edgelist=nx.to_edgelist(G)
width=[v[2]['Value']/50_000_000_000 for v in edgelist]

plt.figure(figsize=(70,40))
nx.draw(G,with_labels=True, node_color=colors,node_size=node_size_list, width=width)
plt.show()